-- Run this in Supabase Dashboard → SQL Editor before using /api/listings.
create table if not exists public.to_let_api (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  price numeric not null check (price >= 0),
  bedrooms integer not null check (bedrooms >= 0),
  bathrooms integer not null check (bathrooms >= 0),
  image_url text,
  square_feet integer,
  description text not null default '',
  contact_number text not null,
  images jsonb not null default '[]'::jsonb,
  category text not null,
  amenities jsonb not null default '{}'::jsonb,
  is_direct_owner boolean not null default true,
  owner_id uuid references auth.users(id),
  owner_name text,
  owner_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists to_let_api_created_at_idx
  on public.to_let_api (created_at desc);
